bistro_site/bistro_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('hub/', include('main_app.urls'))
] + static( settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bistro_site/login/urls.py
from django.urls import path
from login.views import showpage,UserCreateView, show

urlpatterns = [
        path('', UserCreateView.as_view(), name='auth'),
        path('test/', show, name='test'),
        ]

bistro_site/main_app/urls.py
from django.urls import path
from django.contrib.auth import views as authViews
from main_app.views import LoadMainPage,\
        LoadAddProdPage,\
        LoadLookProdPage,\
        LoadEditProdPage,\
        LoadAddRecipePage,\
        LoadLookRecipePage,\
        LoadEditRecipePage,\
        LoadAddDishPage,\
        LoadLookDishPage,\
        LoadEditDishPage,\
        LoadLookDishcompositionPage,\
        LoadAddDishcompositionPage,\
        LoadEditDishcompositionPage,\
        LoadAddDailyReportPage,\
        LoadLookGlobalDailyReportPage,\
        LoadLookLocalDailyReportPage,\
        LoadEditDailyReportPage,\
        LoadLookFinallyReportYearsPage,\
        LoadMakeFinallyReportPage

urlpatterns = [
        path('', LoadMainPage, name='main_page'),
        path('add/product', LoadAddProdPage, name='add_prod'),
        path('look/product', LoadLookProdPage, name='look_prod'),
        path('edit/product', LoadEditProdPage, name='edit_prod'),
        path('add/recipe', LoadAddRecipePage, name='add_recipe'),
        path('look/recipe', LoadLookRecipePage, name='look_recipe'),
        path('edit/recipe', LoadEditRecipePage, name='edit_recipe'),
        path('add/dish', LoadAddDishPage, name='add_dish'),
        path('look/dish', LoadLookDishPage, name='look_dish'),
        path('edit/dish', LoadEditDishPage, name='edit_dish'),
        path('look/dishcomposition', LoadLookDishcompositionPage, name='look_dishcomposition'),
        path('add/dishcomposition', LoadAddDishcompositionPage, name='add_dishcomposition'),
        path('edit/dishcomposition', LoadEditDishcompositionPage, name='edit_dishcomposition'),
        path('add/dailyreport', LoadAddDailyReportPage, name='add_dailyreport'),
        path('look/globaldailyreport', LoadLookGlobalDailyReportPage, name='look_global_dailyreport'),
        path('look/localdailyreport', LoadLookLocalDailyReportPage, name='look_local_dailyreport'),
        path('edit/dailyreport', LoadEditDailyReportPage, name='edit_dailyreport'),
        path('look/finallyreport/years', LoadLookFinallyReportYearsPage, name='look_finallyreport_years'),
        path('make/finallyreport', LoadMakeFinallyReportPage, name='make_finallyreport'),
        path('logout', authViews.LogoutView.as_view(), name='exit'),
        ]

bistro_site/main_app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class dish(models.Model):
    id = models.ForeignKey(
            'recipe',
            primary_key=True,
            on_delete=models.CASCADE
            )
    type = models.CharField(max_length=100)
    img = models.ImageField(upload_to='media/images')


class product(models.Model):
    id = models.IntegerField(
            primary_key=True,
            validators=[MinValueValidator(1), MaxValueValidator(100000)]
            )
    name = models.CharField(max_length=30)
    weight = models.IntegerField()
    calories = models.IntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=2)


class recipe(models.Model):
    id = models.IntegerField(
            primary_key=True,
            validators=[MinValueValidator(1), MaxValueValidator(1000)]
            )
    name = models.CharField(max_length=30)
    cooking_time = models.IntegerField(validators=[MinValueValidator(5), MaxValueValidator(240)])
    cooking_technology = models.CharField(max_length=1000)


class DishComposition(models.Model):
    record_id = models.IntegerField(validators=[MinValueValidator(1)], primary_key=True)
    dish = models.ForeignKey('dish', on_delete=models.CASCADE)
    product = models.ForeignKey('product', on_delete=models.CASCADE)
    product_count = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])


class DailyReport(models.Model):
    id = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100000)], primary_key=True)
    date = models.DateField()
    dish = models.ForeignKey('dish', on_delete=models.CASCADE)
    count = models.IntegerField()

bistro_site/main_app/forms.py
import datetime
from django import forms
from .models import recipe, dish, product,DishComposition, DailyReport


class DailyReportForm(forms.ModelForm):
    date = forms.DateField(input_formats=['%d.%m.%Y'], initial=datetime.date.today(), widget=forms.DateInput(format = '%d.%m.%Y', attrs={'placeholder': 'дд.мм.гггг', 'class': 'input_field'}))
    dish_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Название блюда', 'class': 'input_field'}))
    count = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Количество проданных блюд', 'class': 'input_field'}))

    class Meta:
        model = DailyReport
        fields = ('date', 'dish_name', 'count')


class DishCompositionForm(forms.ModelForm):
    name = forms.CharField(label='Название продукта', widget=forms.TextInput(attrs={'placeholder': 'Название продукта', 'class': 'input_field'}))
    product_count = forms.IntegerField(label='Количество', widget=forms.TextInput(attrs={'placeholder': 'Количество', 'class': 'input_field'}))

    class Meta:
        model = DishComposition
        fields = ('name', 'product_count')


class ProductForm(forms.ModelForm):
    name = forms.CharField(label='Название продукта', widget=forms.TextInput(attrs={'placeholder': 'Название продукта', 'class': 'input_field'}))
    weight = forms.IntegerField(label='Вес продукта', widget=forms.TextInput(attrs={'placeholder': 'Вес продукта в граммах', 'class': 'input_field'}))
    calories = forms.IntegerField(label='Калорийность продукта', widget=forms.TextInput(attrs={'placeholder': 'Калорийность продукта в Ккал', 'class': 'input_field'}))
    price = forms.DecimalField(label='Цена продукта', widget=forms.TextInput(attrs={'placeholder': 'Цена продукта за кг', 'class': 'input_field'}))

    class Meta:
        model = product
        fields = ('name', 'weight', 'calories', 'price')


class RecipeForm(forms.ModelForm):
    name = forms.CharField(label='Название рецепта', widget=forms.TextInput(attrs={'placeholder': 'Название рецепта', 'class': 'input_field'}))
    cooking_time = forms.CharField(label='Время приготовления', widget=forms.TextInput(attrs={'placeholder': 'Время приготовления в минутах', 'class': 'input_field'}))
    cooking_technology = forms.CharField(label='Технология приготовления', widget=forms.Textarea(attrs={'placeholder': 'Технология приготовления', 'class': 'input_field_area'}))
    
    class Meta:
        model = recipe
        fields = ('name', 'cooking_time', 'cooking_technology')

class DishForm(forms.ModelForm):
    name = forms.CharField(label='Название блюда', widget=forms.TextInput(attrs={'placeholder': 'Название блюда', 'class': 'input_field'}))
    type = forms.CharField(label='Тип блюда', widget=forms.TextInput(attrs={'placeholder': 'Тип блюда', 'class': 'input_field'}))
    img = forms.ImageField(label='Картинка', widget=forms.FileInput(attrs={'class': 'input_image', 'accept': 'image/', 'onchange': 'download(this)'}))

    class Meta:
        model = dish
        fields = ('name', 'type', 'img')

bistro_site/main_app/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q, F
from main_app.forms import ProductForm, RecipeForm, DishForm, DishCompositionForm, DailyReportForm
from main_app.models import product, recipe, dish, DishComposition, DailyReport
from main_app.error_checker import CheckProduct,\
        CheckRecipe,\
        CheckDish,\
        CheckDailyreport,\
        CheckDishcomposition

@csrf_exempt
def LoadMakeFinallyReportPage(request):
    daily_reports = DailyReport.objects.raw(
            """
            select main_app_dailyreport.id as id,
            main_app_recipe.name as name,
            main_app_dailyreport.count,
            to_char(main_app_dailyreport."date",'DD.MM.YYYY') as date, 
            round(sum((main_app_product.price/1000.00)*main_app_product.weight*main_app_dishcomposition.product_count*main_app_dailyreport.count),2) as price
            from main_app_dailyreport
            inner join main_app_dishcomposition on main_app_dishcomposition.dish_id = main_app_dailyreport.dish_id 
            inner join main_app_product on main_app_product.id = main_app_dishcomposition.product_id
            inner join main_app_recipe on main_app_dishcomposition.dish_id = main_app_recipe.id
            where main_app_dailyreport.dish_id = main_app_dishcomposition.dish_id
            group by main_app_dailyreport."date", main_app_dailyreport.id, main_app_recipe.name, main_app_dailyreport.count
            order by date;
            """
            )

    finally_sums = DailyReport.objects.raw(
            """
            select 1 as id, extract(year from main_app_dailyreport."date") as date,  round(sum((main_app_product.price/1000.00)*main_app_product.weight*main_app_dishcomposition.product_count*main_app_dailyreport.count),2) as price
            from main_app_dailyreport
            inner join main_app_dishcomposition on main_app_dishcomposition.dish_id = main_app_dailyreport.dish_id 
            inner join main_app_product on main_app_product.id = main_app_dishcomposition.product_id
            inner join main_app_dish on main_app_dishcomposition.dish_id = main_app_dish.id_id
            where main_app_dailyreport.dish_id = main_app_dishcomposition.dish_id
            group by extract(year from main_app_dailyreport."date"), 1
            order by date
            """
            )
    
    daily_reports_results = DailyReport.objects.raw(
            """
            select 1 as id, to_char(main_app_dailyreport."date",'DD.MM.YYYY') as date,  round(sum((main_app_product.price/1000.00)*main_app_product.weight*main_app_dishcomposition.product_count*main_app_dailyreport.count),2) as price
            from main_app_dailyreport
            inner join main_app_dishcomposition on main_app_dishcomposition.dish_id = main_app_dailyreport.dish_id
            inner join main_app_product on main_app_product.id = main_app_dishcomposition.product_id
            inner join main_app_dish on main_app_dishcomposition.dish_id = main_app_dish.id_id
            where main_app_dailyreport.dish_id = main_app_dishcomposition.dish_id
            group by main_app_dailyreport."date", 1
            order by date
            """
            )

    cur_year = None
    cur_year_results = None
    days_results = []
    try:
        cur_year = request.GET['year']
    except:
        pass
    #выбираю текущий год
    for i in finally_sums:
        if cur_year == str(i.date):
            cur_year_results = i
            break
    #заполняю массив с продажами, актуальными на этот год
    for i in daily_reports:
        if i.date.split('.')[2] == cur_year:
            days_results.append(i)
    
    daily_reports_with_dishprices = []
    actually_daily_reports_results = []
    for i in daily_reports_results:
        if i.date.split('.')[2] == cur_year:
            actually_daily_reports_results.append(i)


    #записываю в массив записи о продажах + стоимость за одно блюдо
    for i in days_results:
        record = {'record': i, 'dish_price': round(i.price/i.count, 2)}
        daily_reports_with_dishprices.append(record)

    context = {'days_results': days_results, 'cur_year_results': cur_year_results, 'daily_reports_with_dishprices': daily_reports_with_dishprices, 'cur_year': cur_year, 'actually_daily_reports_results': actually_daily_reports_results}
    return render(request, 'main_app/FinallyReportPath/look_finallyreport.html', context)



@csrf_exempt
def LoadLookFinallyReportYearsPage(request):
    reports = DailyReport.objects.all().order_by('date')

    years = []

    for i in reports:
        year = i.date.year
        if year not in years:
            years.append(year)

    context = {'years': years}
    return render(request, 'main_app/FinallyReportPath/look_years_finallyreport.html', context)



@csrf_exempt
def LoadEditDailyReportPage(request):
    error = ''
    cur_name = None
    cur_date = None
    cur_id = None
    try:
        cur_name = request.GET['name']
        cur_date = request.GET['date']
        cur_id = request.GET['reportID']
    except:
        pass

    if request.method == 'POST':
        error = CheckDailyreport(request)
        if error == '':
            form = DailyReportForm(request.POST)
            if form.is_valid():
            
                if cur_name == None:
                    error = f'Невозможно добавить информацию о продажах, так как блюда с названием {cur_name} не существует.'
                elif cur_date == None:
                    error = f'Невозможно редактировать информацию о продажах, нет продажи этого блюда за {cur_date} число.'
                elif cur_id == None:
                    error = f'Невозможно редактировать информации об этой продаже, так как ее не существует.'
                else:
                    editable_dailyreport = DailyReport.objects.get(id=cur_id)
                    editable_dailyreport.date = editable_dailyreport.date
                    editable_dailyreport.count = form.cleaned_data.get('count')
                    editable_dailyreport.save()
                    return redirect('look_global_dailyreport')

    form = DailyReportForm
    context={'form': form, 'error': error, 'cur_name': cur_name, 'cur_date': cur_date}

    return render(request, 'main_app/DailyReportPath/edit_dailyreport.html', context)



@csrf_exempt
def LoadLookLocalDailyReportPage(request):
    cur_date = ''
    try:
        cur_date = request.GET['date']
    except:
        pass
    # TODO потом разобраться и сделать нормально
    local_reports = DailyReport.objects.raw(
            """
            select main_app_dailyreport.id as id,
            main_app_recipe.name as name,
            main_app_dailyreport.count,
            to_char(main_app_dailyreport."date",'DD.MM.YYYY') as date, 
            round(sum((main_app_product.price/1000.00)*main_app_product.weight*main_app_dishcomposition.product_count*main_app_dailyreport.count),2) as price
            from main_app_dailyreport
            inner join main_app_dishcomposition on main_app_dishcomposition.dish_id = main_app_dailyreport.dish_id 
            inner join main_app_product on main_app_product.id = main_app_dishcomposition.product_id
            inner join main_app_recipe on main_app_dishcomposition.dish_id = main_app_recipe.id
            where main_app_dailyreport.dish_id = main_app_dishcomposition.dish_id
            group by main_app_dailyreport."date", main_app_dailyreport.id, main_app_recipe.name, main_app_dailyreport.count
            order by price;
            """
            )
    if request.method == "POST":
        record = DailyReport.objects.get(id=request.POST['record_id'])
        if request.POST['button_type'] == "удалить":
            record.delete()
            return redirect('look_global_dailyreport')
    context = {'local_reports': local_reports, 'cur_date': cur_date}
    return render(request, 'main_app/DailyReportPath/look_dailyreport_local.html', context)


@csrf_exempt
def LoadLookGlobalDailyReportPage(request):
    # TODO потом разобраться и сделать нормально
    global_reports = DailyReport.objects.raw(
            """
            select 1 as id, to_char(main_app_dailyreport."date",'DD.MM.YYYY') as date,  round(sum((main_app_product.price/1000.00)*main_app_product.weight*main_app_dishcomposition.product_count*main_app_dailyreport.count),2) as price
            from main_app_dailyreport
            inner join main_app_dishcomposition on main_app_dishcomposition.dish_id = main_app_dailyreport.dish_id 
            inner join main_app_product on main_app_product.id = main_app_dishcomposition.product_id
            inner join main_app_dish on main_app_dishcomposition.dish_id = main_app_dish.id_id
            where main_app_dailyreport.dish_id = main_app_dishcomposition.dish_id
            group by main_app_dailyreport."date", 1
            order by date
            """
            )

    context = {'global_reports': global_reports}
    return render(request, 'main_app/DailyReportPath/look_dailyreport_global.html', context)


@csrf_exempt
def LoadAddDailyReportPage(request):
    error = ''
    if request.method == 'POST':
        error = CheckDailyreport(request)
        if error == '':
            form = DailyReportForm(request.POST)
            if form.is_valid():
                new_id = 1
        
                dailyreports = DailyReport.objects.all()
                dailyreports_id = [i.id for i in dailyreports]
                for i in range(1,1001):
                    if i not in dailyreports_id:
                        new_id = i
                        break
                
                dish_name = form.cleaned_data.get('dish_name')
                enabled_recipe = None
                enabled_dish = None
                try:
                    enabled_recipe = recipe.objects.get(name=dish_name)
                    enabled_dish = dish.objects.get(id=enabled_recipe.id)
                except:

bistro_site/main_app/templates/main_app/DishPath/add_dish.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
            <link rel="stylesheet" type="text/css" href="{%static 'css/main_page_style.css'%}">
    </head>

    <body>
       <div class="menu">

            <div class="menu_text bistro_text">Бистро</div>
            {%if request.user.position == "Шеф-повар"%}
                {%include "main_app/shef.html"%}
            {%elif request.user.position == "Кассир"%}
                {%include "main_app/seller.html"%}
            {%elif request.user.position == "Руководитель склада"%}
                {%include "main_app/stock_manager.html"%}
            {%elif request.user.position == "Бухгалтер"%}
                {%include "main_app/accountant.html"%}
            {%endif%}
        </div>

	<div class="main_block">
            <div class="header">
                <div><a href="http://146.185.240.26/hub/logout">Выход</a></div>
            </div>
            <hr>
            {%if request.user.position != "Шеф-повар"%}
            <div class="welcome">Доступ запрещен!</div>
            {%else%}
            <div class="interact_block">
                <div class="description">
                    Добавление блюда
                </div>

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="add_field">
                        {{form.name}}
                    </div>
                    <div class="add_field">
                        {{form.img}}
			<label for="id_img">
                            <span class="input_field-img-icon-wrapper">
                                <img class="input_field-img-icon" src="https://cdn-icons-png.flaticon.com/128/5730/5730886.png" alt="Выбрать файл">
				<script src="{%static 'scripts/img_script.js'%}"></script>
                            </span>
                        </label>
                    </div>
                    <div class="add_field">
                        {{form.type}}
                    </div>
                    <span class="error">{{ error }}</span>
                    <div class="button">
                        <input type="submit" value="Сохранить" class="save">
                    </div>
                </form>
            </div>
            {%endif%}
        </div>

    </body>

    <footer>
    </footer>
</html>

bistro_site/main_app/templates/main_app/DishPath/edit_dish.html
{%load static%} 
<!DOCTYPE html>
<html>
    <head>      
            <link rel="stylesheet" type="text/css" href="{%static 'css/main_page_style.css'%}">
    </head>
                
    <body>  
       <div class="menu">
                
            <div class="menu_text bistro_text">Бистро</div>
            {%if request.user.position == "Шеф-повар"%}
                {%include "main_app/shef.html"%}
            {%elif request.user.position == "Кассир"%}
                {%include "main_app/seller.html"%}
            {%elif request.user.position == "Руководитель склада"%}
                {%include "main_app/stock_manager.html"%}
            {%elif request.user.position == "Бухгалтер"%}
                {%include "main_app/accountant.html"%}
            {%endif%}
        </div>
                
        <div class="main_block">
            <div class="header">
                <div><a href="http://146.185.240.26/hub/logout">Выход</a></div>
            </div>
            <hr>
            {%if request.user.position != "Шеф-повар"%}
            <div class="welcome">Доступ запрещен!</div>
            {%else%}
            <div class="interact_block">
                <div class="description">
		    Редактирование блюда {{editable_dish.id.name}}
                </div>
		<form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
		    <div class="add_field">
			    <input id="id_name" class="input_image" type="text" name="name" value={{editable_dish.id.name}}>
                    </div>
                    <div class="add_field">
                        {{form.img}}
                        <label for="id_img">
                            <span class="input_field-img-icon-wrapper">
                                <img class="input_field-img-icon" src="https://cdn-icons-png.flaticon.com/128/5730/5730886.png" alt="Выбрать файл">
                                <script src="{%static 'scripts/img_script.js'%}"></script>
                            </span>
                        </label>
                    </div>
                    <div class="add_field">
                        {{form.type}}
                    </div>
                    <span class="error">{{ error }}</span>
                    <div class="button">
                        <input type="submit" value="Сохранить" class="save">
                    </div>
                </form>
            </div>
            {%endif%}
        </div>

    </body>

    <footer>
    </footer>
</html>

bistro_site/main_app/templates/main_app/DishPath/look_dish.html
{%load static%}
<!DOCTYPE html>
<html>      
    <head>
            <link rel="stylesheet" type="text/css" href="{%static 'css/main_page_style.css'%}">
    </head>

    <body>
        <div class="menu">

            <div class="menu_text bistro_text">Бистро</div>
            {%if request.user.position == "Шеф-повар"%}
                {%include "main_app/shef.html"%}
            {%elif request.user.position == "Кассир"%}
                {%include "main_app/seller.html"%}
            {%elif request.user.position == "Руководитель склада"%}
                {%include "main_app/stock_manager.html"%}
            {%elif request.user.position == "Бухгалтер"%}
                {%include "main_app/accountant.html"%}
            {%endif%}
        </div>
        <div class="main_block">
            <div class="header">
                <div><a href="http://146.185.240.26/hub/logout">Выход</a></div>
            </div>
            <hr>
            {% if request.user.position != "Шеф-повар" and request.user.position != "Кассир" %}
            <div class="welcome">Доступ запрещен!</div>
            {%else%}
            <div class="interact_block">
                <div class="description">
                    Просмотр блюд
                </div>
                    <table>
                        <tr>
                            <td>id</td>
                            <td>Название</td>
                            <td>Тип блюда</td>
			    <td>Вес</td>
			    <td>Калорийность</td>
                            <td>Состав</td>
                            <td>Картинка</td>
			    {%if request.user.position == "Шеф-повар"%}
                            <td class="last_td"></td>
			    {%endif%}
                        </tr>
                    </table>
                    <div class="table_block">
                        <table>
                        {%for i in dishes%}
                         <tr>
			    <form method="post">
                            <td>{{i.id_id}}</td>
                            <td>{{i.id.name}}</td>
                            <td>{{i.type}}</td>
			    {%if i in dishes_with_compositions%}
			    <td>{{i.weight}}г</td>
			    <td>{{i.calories}}Ккал</td>
			    {%else%}
			    <td>0г</td>
			    <td>0Ккал</td>
			    {%endif%}
                            <td>
                                {%for j in dish_composition%}
				    {%if j.dish_id == i.id_id%}
                                	{{j.product.name}}: {{j.product_count}}<br>
				    {%endif%}
                                {%endfor%}
                            </td>
			    <td><img class="table_img" src="/{{i.img}}"></td>
			    {%if request.user.position == "Шеф-повар"%}
                            <td class="last_td">
				<input type="hidden" value={{i.id_id}} name="record_id">
				<a href="http://146.185.240.26/hub/edit/dish?dishID={{i.id_id}}"><input type="button" class="save" value="редактировать"></a><br><br>
				<a href="http://146.185.240.26/hub/look/dishcomposition?dishID={{i.id_id}}"><input type="button" class="save" value="изменить состав"></a><br><br>
                            	<input type="submit" value="удалить" name="button_type" class="reset">
			    </td>
			    {%endif%}
			    </form>
                        </tr>
                        {%endfor%}
                        </table>
                    </div> 
                </div>  
            </div>  
            {%endif%}
        </div>  
            
            
    </body>
    <footer>
    </footer>
</html>